version: '3.8'
services:
  api:
    container_name: api
    restart: always
    build: .
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - db
    volumes:
    - .:/usr/app

  client:
    build: ./client
    container_name: client_frontend
    ports:
      - '8000:8000'
    volumes:
      - ./client:/src
      - ./client/node_modules
    stdin_open: true
    tty: true

  db:
    container_name: postgres
    image: postgres
    ports:
      - '5433:${DB_PORT}'
    volumes:
      - data:/data/db
    environment:
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
 
volumes: 
 data: {}
 